default:
  target: dev
  outputs:
    core:
      type: mysql
      host: localhost
      user: root
      password: "p@ssw0rd"
      database: core
      schema: core
      port: 3306
    core_extensions:
      type: mysql
      host: localhost
      user: root
      password: "p@ssw0rd"
      database: core_extensions
      schema: core_extensions
      port: 3306